# Generated by Django 5.0.6 on 2024-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adoption_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('upload_file', models.FileField(upload_to='uploads/')),
                ('detection_type', models.CharField(choices=[('covid', 'Covid-19'), ('lungcancer', 'Lung Cancer'), ('pneumonia', 'Pneumonia')], max_length=10)),
            ],
        ),
    ]
