# Generated by Django 5.0.6 on 2024-06-22 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='patient_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='adoption_date',
            field=models.CharField(max_length=100),
        ),
    ]
