# Generated by Django 5.0.6 on 2024-06-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0002_detection_patient_id_alter_detection_adoption_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='detection_type',
        ),
        migrations.AddField(
            model_name='detection',
            name='cancer_status',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='covid_status',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='pneumonia_status',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
