# Generated by Django 5.0.6 on 2024-06-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0004_alter_detection_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to='findings/'),
        ),
    ]
