# Generated by Django 5.0.6 on 2024-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0005_alter_detection_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='adoption_date',
            field=models.DateField(),
        ),
    ]
